### ISSUE TITLE
choose folder for album name / moving to module

### ISSUE THREAD

**Issue by drmcachr** [TwiggyG2K23/psIMMICH#3]
I have another question for album names

my directory is folder0/folder1/file.jpg

I want to name album as folder1, but I noticed the script created album as folder0_folder1, is there any way to choose folder?

and I suppose this script only create exteral lib, but it also create album from upload path

![image](https://github.com/TwiggyG2K23/psIMMICH/assets/13805378/f997adca-ea7b-4918-a4bb-5081d45e05ff)

**Comment by TwiggyG2K23** [comment]
Ah i understand :) its not possible at the moment, but i can implement it. Good idea.

**Comment by TwiggyG2K23** [comment]
Good Morning.. here in germany :P

You can try now the feature u wanted. MAybe its a bit confusing because i decided to move all to module structure and push it to PSGallery when done. Until then please use the loading.ps1 . Now you are working with Cmdlets and parameter. Please use get-help as usual in powershell for further informations.

Replace _param.ps1 with your own and delete the "Loading Functions" PArt ore replace the values in the existing with your own. Load loading.ps1 and then you can use the cmdlets in same console session.

For your feature request i think the call is

 1. remove-imAlbum -all
 2. new-imAlbumByFolder -lastFoldername

**Comment by TwiggyG2K23** [comment]
Perfect :)
